version: '3'

services:
  backend:
    build: ./server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - .env
    depends_on:
      - keycloak
      - db
    networks:
      - app-single_thread

  frontend:
    build:
      context: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - app-single_thread

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=viki
      - MONGO_INITDB_ROOT_PASSWORD=123
      - MONGO_INITDB_DATABASE=db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-single_thread
