version: '3'

services:
  backend:
    build: ./server
    ports:
      - '3000:3000'
    environment: /.env
    depends_on:
      - db
    networks:
      - app-single_thread

  frontend:
    build:
      context: ./client
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app-single_thread

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: viki
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    ports:
      - '5432:5432'
    networks:
      - app-single_thread
